version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run: node sample.js
      - run: test `./bin/ppp 5 large:1500 macos-large:1000 dlc:100` -eq 105
